### ISSUE TITLE
AutoHotkey v2

### ISSUE THREAD

**Issue by asheroto** [chocolatey-community/chocolatey-packages#2378] opened 2023-12-18 19:14 UTC
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

2.0

### Download location

https://www.autohotkey.com/

### Package Page

https://community.chocolatey.org/packages/autohotkey

**Comment by asheroto** [comment] 2023-12-18 19:23
AutoHotkey 1.x is considered deprecated now.

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/49938263/b6966511-00b5-4ff7-9c38-f7b5226fbcd8)

According to this page, it appears that AutoHotkey is backwards compatible:
https://www.autohotkey.com/boards/viewtopic.php?f=24&t=112989

Note that the installation folder for AutoHotkey 1 is generally
`C:\Program Files\AutoHotkey`

but AutoHotkey 2 is
C:\Program Files\AutoHotkey\v2

In testing, v1 was not removed when I installed v2.

Looks like they can be ran side-by-side:
https://www.autohotkey.com/boards/viewtopic.php?f=2&t=113012

As this is a major version release, I'm not quite sure how it should be handled with Chocolatey. You can liken their methodology similar to how Microsoft Office comes out with a newer version. It's not just an update, but a whole new version.

With this new version, there is now a launcher/dash area where you can modify settings. I mention this because scripts that are launched will, by default, open this version selection screen...

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/49938263/7ca7a1bf-1e33-4c94-bc49-496494a104cd)

In the dash, the default options are...

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/49938263/4fb8f469-aaba-4049-b988-d0eb4c575a12)

Saying that to say, if someone has a script that is set to launch purely by running the `ahk` file, it may not launch because it's going to present them with this version selection window. Might consider this if wanting to update.

Perhaps there should be a new package, like autohotkey2, since there are so many changes?

**Comment by asheroto** [comment] 2023-12-18 19:26
I also noticed this package, but it's confusing because although it's version 2 in portable, it is not in the installer:
https://community.chocolatey.org/packages/autohotkey.portable/2.0.10

**Comment by asheroto** [comment] 2023-12-18 19:32
As another thought, in the configuration if you set this to "Use v1.x" then all scripts will continue to work so long as v1 is installed.

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/49938263/b5465e1f-a5b9-4602-835f-5c3972c366b8)

That setting corresponds to this:
```
[HKEY_CURRENT_USER\Software\AutoHotkey\Launcher]
"Fallback"="1"
```

**Comment by AdmiringWorm** [comment] 2024-05-08 08:30
This is a duplicate of #1710.

**Closed by AdmiringWorm** 2024-05-08 08:30 UTC
Labels: 0 - Backlog, Up for grabs, Needs new updater, Outdated
