### ISSUE TITLE
virtualbox

### ISSUE THREAD

**Issue by roelschroeven** [chocolatey-community/chocolatey-packages#2144] opened 2023-02-16 09:52 UTC
### Chocolatey Version

1.2.1

### Chocolatey License

None

### Package Version

7.0.6 -> 7.0.6.20230201

### Current Behaviour

Chocolatey tries and fails to upgrade virtualbox from 7.0.6 to 7.0.6.20230201; see error message below in "Steps To Reproduce" and linked log.

As far as I can see 7.0.6.20230201 is not even an officially released version?!? If I download the newest version from the VirtualBox website, I get VirtualBox-7.0.6-155176-Win.exe. Indeed, that's the file choco tries to install too, but it put it in a directory named 7.0.6.20230201!?

### Expected Behaviour

I would expect Chocolatey to install the officially released version, 7.0.6-155176. When that version is already installed, like it is on my computer, I would expect Chocolatey not to try an update.

### Steps To Reproduce

Pre-condition: VirtualBox installed and at version 7.0.6-155176
Environment: Windows Powershell running as Administrator
Run: choco upgrade virtualbox
Output:
```
Chocolatey v1.2.1
Upgrading the following packages:
virtualbox
By upgrading, you accept licenses for the packages.

You have virtualbox v7.0.6 installed. Version 7.0.6.20230201 is available based on your source(s).
virtualbox is not running
Progress: Downloading virtualbox 7.0.6.20230201... 100%

virtualbox v7.0.6.20230201 [Approved]
virtualbox package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing virtualbox...
VirtualBox-7.0.6-155176-Win.exe: error: Installation failed! Error: Onherstelbare fout bij installatie.
Microsoft.PowerShell.Commands.WriteErrorException
ERROR: Running ["C:\Users\Roel\AppData\Local\Temp\chocolatey\virtualbox\7.0.6.20230201\VirtualBox-7.0.6-155176-Win.exe" -s -l -msiparams REBOOT=ReallySuppress ALLUSERS=1 ] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of virtualbox was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - virtualbox (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'.
 See log for details.
```

("Onherstelbare fout bij installatie" means "Unrecoverable error during installation.")

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19045.0
- PowerShell Version: 5.1.19041.2364 Desktop
```

### Chocolatey Log

```shell
https://gist.github.com/roelschroeven/b1d58ee6433e6f7182f1aaea34c7b576
```

**Comment by pauby** [comment] 2023-02-16 10:40
This is a duplicate of [this issue comment onwards](https://github.com/chocolatey-community/chocolatey-packages/issues/2132#issuecomment-1414122596). This [issue](https://github.com/chocolatey-community/chocolatey-packages/issues/2137) has also been created to hewlp resolve these issues in future.

**Closed** 2023-02-16 10:40 UTC
Labels: Bug
