### ISSUE TITLE
(kitty)

### ISSUE THREAD

**Issue by DavidBuj** [chocolatey-community/chocolatey-packages#1802] opened 2022-02-16 22:26 UTC
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

0.76.0.8

### Download location

https://www.fosshub.com/KiTTY.html

### Package Page

https://community.chocolatey.org/packages/kitty

**Comment by TheCakeIsNaOH** [comment] 2022-02-17 03:29
Checklist not followed, this is a duplicate of #1768

**Closed by TheCakeIsNaOH** 2022-02-17 03:29 UTC
Labels: Outdated
