### ISSUE TITLE
update thunderbird desktop package

### ISSUE THREAD

**Issue by kazenguyen97** [chocolatey-community/chocolatey-packages#2551] opened 2024-10-14 10:18 UTC
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).
- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.

### New Software Version

128.3.1

### Download location

https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/128.3.1esr/win64/en-US/Thunderbird%20Setup%20128.3.1esr.exe

### Package Page

https://community.chocolatey.org/packages/thunderbird

**Comment by TheCakeIsNaOH** [comment] 2024-10-14 23:04
Duplicate of #2515

**Closed by TheCakeIsNaOH** 2024-10-14 23:04 UTC
Labels: Outdated
