### ISSUE TITLE
(Tixati) Installation failure

### ISSUE THREAD

**Issue by n0phx** [chocolatey-community/chocolatey-packages#2211] opened 2023-04-08 18:20 UTC
### Chocolatey Version

1.3.1

### Chocolatey License

None

### Package Version

3.14

### Current Behaviour

Running the installation from a command prompt with administrator privileges fails when executing the Autohotkey installer:

![image](https://user-images.githubusercontent.com/1327327/230736874-b90c3d1b-8722-4cc3-ba25-223e98b610f0.png)

### Expected Behaviour

Perform installation successfully, without syntax errors.

### Steps To Reproduce

Execute choco install tixati -y from a command prompt with administrator privileges.

### Environment

```markdown
- Operating System: Windows 10
- PowerShell Version: /
- Shell: /
```

### Chocolatey Log

```shell
https://gist.github.com/n0phx/484f9a2214341a7d606d2c5f3f0b8b5c
```

**Comment by pauby** [comment] 2023-04-08 19:03
This is a duplicate of #2182

**Closed by pauby** 2023-04-08 19:03 UTC
Labels: Bug
