### ISSUE TITLE
(sqlite3) Does not install 64-bit version

### ISSUE THREAD

**Issue by djwashburn** [chocolatey-community/chocolatey-packages#2486] opened 2024-06-10 16:21 UTC
### Checklist

- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.
- [X] I have verified that this is happening in the latest available version of the package.

### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

3.43.2

### Current Behaviour

Installing on a 64-bit machine installs the 32-bit version instead.

`choco uninstall sqlite` fails to fully uninstall - the files are not deleted or removed from the path, which leads to them hiding later installs done by methods other than chocolatey, causing the user to have to track down and delete the chocolatey installation manually.

### Expected Behaviour

Installing on a 64-bit machine should install the 64-bit version by default. Uninstalling should delete files and remove them from the path.

### Steps To Reproduce

`choco install sqlite`

Open a new shell

Run sqlite3

Try to load a 64-bit library (such as 64-bit version of [xlite](https://github.com/x2bool/xlite?tab=readme-ov-file) - `.load xlite`

Fails with "%1 is not a valid Win32 application" error

### Environment

```markdown
- Operating System: Windows 10 (Microsoft Windows NT 10.0.19045.0)
- PowerShell Version: 5.1.19041.4412
- Shell: git bash or Windows PowerShell in Windows Terminal
```

### Chocolatey Log

```shell
https://gist.github.com/djwashburn/9b74a6e8ba6a34bce3e55b7fb1d831e8
```

**Comment by pauby** [comment] 2024-06-11 09:00
The logs provided don't have any mention of sqlite.

I installed `sqlite` here, and it installed the 64-bit version as expected.

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/12760779/30be8077-5daf-4394-ab09-b19d5ce2c7f7)

The package places the sqlite files into `$env:ChocolateyInstall\lib\sqlite\tools`. Upon uninstall, that folder is removed.

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/12760779/a19380a7-b349-4aa8-b88f-374a1d490a34)

The hash for the sqllite3.dll in the tools folder is `E0B28EDF0584FCB2FC88FFB38D8B29E227037B23FA2221A9F76B7BD3D26F7CBA`:

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/12760779/9ec8d9d7-8423-4e2c-a789-bf94c0c26fea)

The hash for the sqlite3.dll in the sqllite-dll-win64-x64 archive used for the installation is `e0b28edf0584fcb2fc88ffb38d8b29e227037b23fa2221a9f76b7bd3d26f7cba`, which is the same:

![image](https://github.com/chocolatey-community/chocolatey-packages/assets/12760779/d2642ae4-343f-44ce-918c-29bfaf6c74eb)

If `xlite` doesn't work with it (which I've confirmed) then this could mean many things. The package installs the 64-but version of sqlite as it is supposed to and that's all it is expected to do.

**Comment by corbob** [comment] 2024-06-13 18:40
The issue here might actually be the opposite. As per the note that was just merged in #2342, the 32 bit version is no longer being shipped, and so it's not being installed.

**Comment by dgalbraith** [comment] 2024-06-21 21:23
This looks like an attempt to use 64-bit version of `sqlite` with a 32-bit version of `xlite`.  Functions as expected using a 64-bit version:

<img width="855" alt="image" src="https://github.com/chocolatey-community/chocolatey-packages/assets/1270002/e81fc533-7347-4190-a0b3-37b9b6e6accc">

**Comment by pauby** [comment] 2024-06-22 05:54
Given all of the above comments, and their being no response from @djwashburn, in going to go ahead and close this. We can always reopen it if necessary.

**Closed** 2024-06-22 05:55 UTC
Labels: 0 - Waiting on User
