### ISSUE TITLE
(python3): add user packages scripts path to `PATH` env on install/update

### ISSUE THREAD

**Issue by soredake** [chocolatey-community/chocolatey-packages#2072] opened 2022-12-04 18:44 UTC
### Chocolatey Version

1.2.0

### Chocolatey License

None

### Package Version

3.11.0

### Current Behaviour

Right now python3 is not adding user packages bin path `C:\Users\<path>\AppData\Roaming\Python\Python<version>\Scripts` to `PATH` env leading to inability to launch installed scripts from packages installed with `--user` flag:
```
PS C:\Users\user> pip install --user internetarchive
Installing collected packages: jsonpatch, idna, contextlib2, colorama, charset-normalizer, certifi, tqdm, schema, requests, internetarchive
  WARNING: The script normalizer.exe is installed in 'C:\Users\user\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm.exe is installed in 'C:\Users\user\AppData\Roaming\Python\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  DEPRECATION: internetarchive is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for internetarchive ... done
Successfully installed certifi-2022.9.24 charset-normalizer-2.1.1 colorama-0.4.6 contextlib2-21.6.0 idna-3.4 internetarchive-3.0.2 jsonpatch-1.32 requests-2.28.1 schema-0.7.5 tqdm-4.64.1


PS C:\Users\user> ia
ia : The term 'ia' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ia
+ ~~
    + CategoryInfo          : ObjectNotFound: (ia:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Expected Behaviour

python3 package should add this path to `PATH` env on install/update to make script launch-able after installing them with `--user` option. 

### Steps To Reproduce

1. Install python3 package.
2. do `pip install --user internetarchive`
3. Re-launch terminal and try to launch `ia`
4. You can't.

### Environment

```markdown
- Operating System: Windows 11 Pro
- PowerShell Version: 5.1.22000.832
- Shell: Windows Terminal
```

### Chocolatey Log

```shell
https://gist.github.com/soredake/7b3ee956833041e723ac03f402aaa9a1
```

### Anything else?

winget package for example installs in user-mode and this path is added to `PATH`.

**Comment by pauby** [comment] 2022-12-05 11:17
This isn't a bug in the package. I've removed that label and added 'Enhancement'.

**Comment by pauby** [comment] 2022-12-05 11:33
The `python3` package is installed for all users on the system using [`InstallAllUsers=1`](https://github.com/chocolatey-community/chocolatey-packages/blob/master/automatic/python3/tools/helpers.ps1#L43). Using `PrependPath=1` (which is what is used unless you pass an `InstallDir32` package parameter) it ['Prepend install and Scripts directories to PATH and add .PY to PATHEXT'](https://docs.python.org/3/using/windows.html#installing-without-ui).

You are installing `internetarchive` as a user install. That path is not added by the installer because `python3` is installed for all users. If you run `pip install internetarchive` and then run `ia` it works, because it is installing that for all users and that path has been added.

So the issue is that you will need to add your user path manually.

**Comment by soredake** [comment] 2022-12-08 06:49
> If you're looking to add the functionality, you should look to submit a PR to add it.

I'm just a regular, i don't have skill to create choco packages, so i opened https://github.com/chocolatey-community/chocolatey-package-requests/issues/1389

**Comment by pauby** [comment] 2022-12-08 12:56
I'm a regular user too. This might be a good opportunity to look at creating that package yourself.

**Comment by soredake** [comment] 2023-02-07 09:06
Yes, still relevant.

**Comment by pauby** [comment] 2023-02-07 09:35
@soredake If you're unable to pick this up, then I would argue that this is no longer relevant, and, we should look to close this issue. Unfortunately, nobody else has shown interest in picking it up.

**Closed** 2023-02-07 09:40 UTC
Labels: Enhancement, 0 - Waiting on User, Pending closure
