### ISSUE TITLE
mpc-hc-clsid2

### ISSUE THREAD

**Issue by dsan0815** [chocolatey-community/chocolatey-packages#2066] opened 2022-11-18 15:05 UTC
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

1.9.24

### Download location

https://github.com/clsid2/mpc-hc/releases

**Comment by brogers5** [comment] 2022-11-19 02:43
Related: #2007

**Comment by AdmiringWorm** [comment] 2022-12-16 11:14
Duplicate of #2007

**Closed by AdmiringWorm** 2022-12-16 11:14 UTC
Labels: Outdated
