### ISSUE TITLE
(spotify) Installation progress hangs / terminates after task creation -> Possible fix

### ISSUE THREAD

**Issue by rorar** [chocolatey-community/chocolatey-packages#2353] opened 2023-11-16 04:06 UTC
### Chocolatey Version

2.2.2

### Chocolatey License

None

### Package Version

1.2.24.756

### Current Behaviour

While installing on a brand new laptop, the script outputs something like this:
2023-10-10 19:40:34,316 20960 [INFO ] - SUCCESS: The scheduled task "spotify" has successfully been created.
2023-10-10 19:40:34,326 20960 [INFO ] - SUCCESS: Attempted to run the scheduled task "spotify".
2023-10-10 19:40:35,349 20960 [INFO ] - SUCCESS: The scheduled task "spotify" was successfully deleted.
2023-10-10 20:25:31,000 20960 [WARN ] - Chocolatey timed out waiting for the command to finish. The timeout

### Expected Behaviour

Script just installs spotify

### Steps To Reproduce

1. Have Chocolatey installed
2. run `choco install spotify`

### Environment

```markdown
- Operating System:
Windows 11 / Microsoft Windows NT 10.0.22621.0
- PowerShell Version:
5.1.22621.2428
- Shell:
```

### Chocolatey Log

```shell
---
```

### Anything else?

I've written a script that fixes the issue, you might want to check it out:
https://github.com/rorar/Chocolatey-Spotify-Installation-Fix/tree/main

**Comment by pauby** [comment] 2023-11-16 11:50
This is a duplicate of #941.

**Closed by pauby** 2023-11-16 11:50 UTC
Labels: Bug
