### ISSUE TITLE
(freecad) ERROR: The remote file either doesn't exist, is unauthorized...

### ISSUE THREAD

**Issue by thosoo** [chocolatey-community/chocolatey-packages#1800] opened 2022-02-15 12:28 UTC
### Chocolatey Version

0.12.1

### Package Version

0.19.3

### Current Behaviour

Installation fails.

```PS C:\Users\thies> choco install freecad
Chocolatey v0.12.1
Installing the following packages:
freecad
By installing, you accept licenses for the packages.
Progress: Downloading freecad 0.19.3... 100%

freecad v0.19.3 [Approved]
freecad package files install completed. Performing other installation steps.
The package freecad wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): a

Attempt to get headers for https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
Downloading freecad 64 bit
  from 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
The install of freecad was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\freecad\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - freecad (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\freecad\tools\chocolateyInstall.ps1'.
 See log for details.

Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip-top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare```

### Expected Behaviour

installs without issues

### Steps To Reproduce

`choco install freecad`

### Environment

```markdown
- Operating System:win11
- PowerShell Version:7.3.1
- Shell:windows terminal pwsh 7.3.1
```

### Chocolatey Log

```shell
2022-02-15 13:20:22,294 19476 [DEBUG] - ---------------------------Script Execution---------------------------
2022-02-15 13:20:22,298 19476 [DEBUG] - Running 'ChocolateyScriptRunner' for freecad v0.19.3 with packageScript 'C:\ProgramData\chocolatey\lib\freecad\tools\chocolateyInstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\freecad', installArguments: '', packageParameters: '',
2022-02-15 13:20:22,300 19476 [DEBUG] - Running 'C:\ProgramData\chocolatey\lib\freecad\tools\chocolateyInstall.ps1'
2022-02-15 13:20:22,384 19476 [DEBUG] - Running Install-ChocolateyPackage -url 'https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x32-installer.exe' -silentArgs '/S' -checksum 'A3C00E00E5321D9786C56D58C501F8A8E43BA9D25F7147CD8B9C869D744BE514' -checksum64 'D4CC7869B7BB1C3E5C7B4FE75A578BC825D191D4CD4054FA015D7AE83C6F51F7' -checksumType 'sha256' -packageName 'freecad' -fileType 'exe' -validExitCodes '0' -checksumType64 'sha256' -url64bit 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe' 
2022-02-15 13:20:22,433 19476 [DEBUG] - Running Get-ChocolateyWebFile -packageName 'freecad' -fileFullPath 'C:\Users\thies\AppData\Local\Temp\chocolatey\freecad\0.19.3\freecadInstall.exe' -url 'https://github.com/FreeCAD/FreeCAD/releases/download/0.18.4/FreeCAD-0.18.4.980bf90-WIN-x32-installer.exe' -url64bit 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe' -checksum 'A3C00E00E5321D9786C56D58C501F8A8E43BA9D25F7147CD8B9C869D744BE514' -checksumType 'sha256' -checksum64 'D4CC7869B7BB1C3E5C7B4FE75A578BC825D191D4CD4054FA015D7AE83C6F51F7' -checksumType64 'sha256' -options 'System.Collections.Hashtable' -getOriginalFileName 'True' 
2022-02-15 13:20:22,438 19476 [DEBUG] - Running Get-ProcessorBits -compare '64' 
2022-02-15 13:20:22,447 19476 [DEBUG] - CPU is 64 bit
2022-02-15 13:20:22,456 19476 [DEBUG] - Setting url to 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe' and bitPackage to 64
2022-02-15 13:20:22,475 19476 [DEBUG] - Running Get-WebFileName -url 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe' -defaultName 'freecadInstall.exe' 
2022-02-15 13:20:23,998 19476 [DEBUG] - Url request/response failed - file name will be 'freecadInstall.exe':  Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
2022-02-15 13:20:24,000 19476 [DEBUG] - Running Get-WebHeaders -url 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe' -ErrorAction 'Stop' 
2022-02-15 13:20:24,007 19476 [DEBUG] - Setting the UserAgent to 'chocolatey command line'
2022-02-15 13:20:24,008 19476 [DEBUG] - Request Headers:
2022-02-15 13:20:24,009 19476 [DEBUG] -   'Accept':'*/*'
2022-02-15 13:20:24,019 19476 [DEBUG] -   'User-Agent':'chocolatey command line'
2022-02-15 13:20:25,178 19476 [INFO ] - Attempt to get headers for https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe failed.
  The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found."
2022-02-15 13:20:25,185 19476 [INFO ] - Downloading freecad 64 bit
  from 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe'
2022-02-15 13:20:25,208 19476 [DEBUG] - Running Get-WebFile -url 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe' -fileName 'C:\Users\thies\AppData\Local\Temp\chocolatey\freecad\0.19.3\freecadInstall.exe' -options 'System.Collections.Hashtable' 
2022-02-15 13:20:25,212 19476 [DEBUG] - Setting request timeout to  30000
2022-02-15 13:20:25,213 19476 [DEBUG] - Setting read/write timeout to  2700000
2022-02-15 13:20:25,213 19476 [DEBUG] - Setting the UserAgent to 'chocolatey command line'
2022-02-15 13:20:27,377 19476 [ERROR] - ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://github.com/FreeCAD/FreeCAD/releases/download/0.19.3/FreeCAD-0.19.3-WIN-x64-installer-1.exe'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (404) Not Found." 
This package is likely not broken for licensed users - see https://docs.chocolatey.org/en-us/features/private-cdn.
2022-02-15 13:20:27,429 19476 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\freecad\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '404'.
2022-02-15 13:20:27,434 19476 [DEBUG] - Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
2022-02-15 13:20:27,517 19476 [DEBUG] - Command ['"C:\WINDOWS\System32\shutdown.exe" /a'] exited with '1116'
2022-02-15 13:20:27,602 19476 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\freecad'
2022-02-15 13:20:27,603 19476 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\freecad\freecad.nupkg'
  with checksum '566B9ADC0693A7EBFF7A650EAD745634'
2022-02-15 13:20:27,604 19476 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\freecad\freecad.nuspec'
  with checksum '8FD8C95544BBC14FA43008BFF72E1B82'
2022-02-15 13:20:27,604 19476 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\freecad\tools\chocolateyInstall.ps1'
  with checksum '6F60BE5D3CD8E6DF582E26D62466366B'
2022-02-15 13:20:27,605 19476 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\freecad\tools\chocolateyUninstall.ps1'
  with checksum '9CFEB84588F63CC9C58FAEFC444B37A8'
2022-02-15 13:20:27,606 19476 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\freecad\tools\helper.ps1'
  with checksum '3A764D248C2F330FC546975A3C50DF06'
2022-02-15 13:20:27,608 19476 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\.chocolatey\freecad.0.19.3".
2022-02-15 13:20:27,617 19476 [DEBUG] - There was no original file at 'C:\ProgramData\chocolatey\.chocolatey\freecad.0.19.3\.files'
2022-02-15 13:20:27,623 19476 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\freecad.0.19.3\.arguments".
2022-02-15 13:20:27,624 19476 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\freecad.0.19.3\.extra".
2022-02-15 13:20:27,624 19476 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\freecad.0.19.3\.version".
2022-02-15 13:20:27,624 19476 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\freecad.0.19.3\.sxs".
2022-02-15 13:20:27,625 19476 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\freecad.0.19.3\.pin".
2022-02-15 13:20:27,626 19476 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2022-02-15 13:20:27,626 19476 [ERROR] - The install of freecad was NOT successful.
2022-02-15 13:20:27,628 19476 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\freecad\tools\chocolateyInstall.ps1'.
 See log for details.
2022-02-15 13:20:27,631 19476 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\lib-bad".
2022-02-15 13:20:27,634 19476 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\freecad'
 to 'C:\ProgramData\chocolatey\lib-bad\freecad'
2022-02-15 13:20:29,651 19476 [DEBUG] - Attempting to delete file "C:\Users\thies\AppData\Local\NuGet\Cache\freecad.0.19.3.nupkg".
2022-02-15 13:20:29,660 19476 [WARN ] - 
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2022-02-15 13:20:29,666 19476 [INFO ] - 
2022-02-15 13:20:29,668 19476 [ERROR] - Failures
2022-02-15 13:20:29,670 19476 [ERROR] -  - freecad (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\freecad\tools\chocolateyInstall.ps1'.
 See log for details.
2022-02-15 13:20:29,673 19476 [WARN ] - 
Did you know the proceeds of Pro (and some proceeds from other
 licensed editions) go into bettering the community infrastructure?
 Your support ensures an active community, keeps Chocolatey tip-top,
 plus it nets you some awesome features!
 https://chocolatey.org/compare
2022-02-15 13:20:29,676 19476 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2022-02-15 13:20:29,694 19476 [DEBUG] - Exiting with 404
```

**Comment by RedBaron2** [comment] 2022-02-16 04:44
@thosoo 
Thanks for bringing this issue to light. A newer version of the updater for this package is being worked on to fix this issue.  Please be patient will the testing and PR approval process for this package.

**Comment by pauby** [comment] 2022-02-21 11:15
Closing this as a duplicate of #1637

**Closed by pauby** 2022-02-21 11:15 UTC
Labels: Duplicate
