### ISSUE TITLE
(git.install) If a newer version of git is already installed, installing git via chocolatey will fail

### ISSUE THREAD

**Issue by mew1033** [chocolatey-community/chocolatey-packages#2107] opened 2023-01-06 18:19 UTC
### Chocolatey Version

1.2.0

### Chocolatey License

None

### Package Version

2.39.0

### Current Behaviour

I installed git 2.39.0.2 manually to see what options were available in the installer. Then I tried to install the chocolatey package with those same flags (I didn't uninstall the previous version). It kept failing. Eventually I was able to run the same command chocolatey was running remove the `/VERYSILENT /SUPPRESSMSGBOXES` flags. It showed a dialog box warning me that I was about to downgrade and asking if I was sure. Regardless of what I want to do, chocolatey was failing because it couldn't answer that message box.

### Expected Behaviour

Any option is better than what happens now (Unhelpful error message with no logs). Any of the following would probably be fine:

- Spit out a better error telling the user they need to uninstall the previous version first
- Automatically allow downgrading
- Require a parameter to be passed in to allow downgrading

### Steps To Reproduce

1. Install git 2.39.0.2 manually via the installer
2. Try to install git.install 2.39

### Environment

```markdown
- Operating System: Windows 11
```

### Chocolatey Log

```shell
2023-01-06 11:03:04,173 10944 [DEBUG] - Elevating permissions and running ["C:\ProgramData\chocolatey\lib\git.install\tools\Git-2.39.0-64-bit.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOCANCEL /SP- /LOG /COMPONENTS="icons,assoc,assoc_sh,,,,gitlfs,icons\quicklaunch" /o:CURLOption=WinSSL /o:SSHOption=ExternalOpenSSH /o:EditorOption=VisualStudioCode ]. This may take a while, depending on the statements.
2023-01-06 11:03:05,303 10944 [DEBUG] - Command ["C:\ProgramData\chocolatey\lib\git.install\tools\Git-2.39.0-64-bit.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOCANCEL /SP- /LOG /COMPONENTS="icons,assoc,assoc_sh,,,,gitlfs,icons\quicklaunch" /o:CURLOption=WinSSL /o:SSHOption=ExternalOpenSSH /o:EditorOption=VisualStudioCode ] exited with '1'.
2023-01-06 11:03:05,344 10944 [ERROR] - ERROR: Running ["C:\ProgramData\chocolatey\lib\git.install\tools\Git-2.39.0-64-bit.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOCANCEL /SP- /LOG /COMPONENTS="icons,assoc,assoc_sh,,,,gitlfs,icons\quicklaunch" /o:CURLOption=WinSSL /o:SSHOption=ExternalOpenSSH /o:EditorOption=VisualStudioCode ] was not successful. Exit code was '1'. See log for possible error messages.
2023-01-06 11:03:05,347 10944 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\git.install\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '/NoShellIntegration /SChannel /NoOpenSSH /Editor:VisualStudioCode' -preRunHookScripts $null -postRunHookScripts $null'] exited with '1'.
```
```


### Anything else?

_No response_

**Comment by pauby** [comment] 2023-01-15 17:23
I can't reproduce this on Windows Server 2019.

![image](https://user-images.githubusercontent.com/12760779/212556704-9b3ae679-9ada-470d-a35e-8b4c3b14ec0f.png)

**Comment by pauby** [comment] 2023-01-15 17:37
Can't reproduce on Windows 10 either:

![image](https://user-images.githubusercontent.com/12760779/212557332-c6f75b63-4860-4840-bb87-af626ab25f2e.png)

**Comment by pauby** [comment] 2023-03-04 17:41
I'm going to go ahead and close this, but we can reopen it if necessary.

**Closed by pauby** 2023-03-04 17:41 UTC
Labels: Bug, 0 - Waiting on User
