### ISSUE TITLE
autohotkey and autohotkey (install)

### ISSUE THREAD

**Issue by nykBM** [chocolatey-community/chocolatey-packages#2503] opened 2024-07-07 20:41 UTC
### Checklist

- [X] I have verified that this is the correct repository, and the package is maintained by the chocolatey-community user.
- [X] I have verified that this is happening in the latest available version of the package.

### Chocolatey Version

2.3.0

### Chocolatey License

None

### Package Version

2.0.18

### Current Behaviour

Waiting for the update to 2.0.18 from 1.1.37.1.  The package for autohotkey and autohotkey (install) are waiting for maintainer actions to release them for general use.

### Expected Behaviour

autohotkey is update to 2.0.18 when I run choco upgrade

### Steps To Reproduce

1. run choco upgrade all -y in PowerShell (administrator mode)
2. Does not update autohotkey or autohotkey (install) to V 2.0.18

### Environment

```markdown
- Operating System: Windows 10
- PowerShell Version: 5.1.19041
- Shell: NA
```

### Chocolatey Log

```shell
I do not think a log is needed for the case that the packages are waiting for some maintainer step.
```

**Comment by AdmiringWorm** [comment] 2024-07-08 08:39
There is already an issue for autohotkey being duplicated, as such I will be closing this issue in favor of the existing issue.

**Comment by AdmiringWorm** [comment] 2024-07-08 08:39
Duplicate of #2472

**Closed by AdmiringWorm** 2024-07-08 08:39 UTC
Labels: Bug
