### ISSUE TITLE
(virtualbox)  Fatal error during installation

### ISSUE THREAD

**Issue by tranquilcarbon** [chocolatey-community/chocolatey-packages#2214] opened 2023-04-12 11:44 UTC
### Chocolatey Version

1.3.1

### Chocolatey License

None

### Package Version

7.0.6 -> 7.0.6.20230201 

### Current Behaviour

For a few months, I have been unable to update VirtualBox. running the command: choco upgrade VirtualBox results in the following output:
```
Chocolatey v1.3.1
Upgrading the following packages:
virtualbox
By upgrading, you accept licenses for the packages.

You have virtualbox v7.0.6 installed. Version 7.0.6.20230201 is available based on your source(s).
virtualbox is not running
Progress: Downloading virtualbox 7.0.6.20230201... 100%

virtualbox v7.0.6.20230201 [Approved]
virtualbox package files upgrade completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing virtualbox...
Microsoft.PowerShell.Commands.WriteErrorException
VirtualBox-7.0.6-155176-Win.exe: error: Installation failed! Error: Fatal error during installation.
ERROR: Running ["C:\Users\Admin\AppData\Local\Temp\chocolatey\virtualbox\7.0.6.20230201\VirtualBox-7.0.6-155176-Win.exe" -s -l -msiparams REBOOT=ReallySuppress ALLUSERS=1 ] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of virtualbox was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - virtualbox (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'.
 See log for details.
```

i believe the error occurs because VirtualBox reports it's version differently to how chocolatey reports it, VirtualBox reports it's version as 7.0.6 while chocolatey reports it as 7.0.6.20230201. 

### Expected Behaviour

either update VirtualBox to 7.0.6.20230201 or recognise the latest version is installed and remove it from the outdated list

### Steps To Reproduce

1. install virtualbox 7.0.6 from the oracle VirtualBox website
2. attempt to update VirtualBox through the command "choco upgrade all" or "choco upgrade VirtualBox"
3. wait for the update process to fail.

### Environment

```markdown
- Operating System:Microsoft Windows NT 10.0.19045.0
- PowerShell Version:5.1.19041.2673
- Shell:CMD
```

### Chocolatey Log

```shell
https://gist.github.com/tranquilcarbon/167f4274ea876c03575e8bf82db1fac9
```

**Comment by pauby** [comment] 2023-04-14 13:38
This is a duplicate of #2144 and may be fixed by #2137

I suggest we leave this one open so that other people can see it and don't have to raise another issue because of it.

**Closed** 2024-10-05 04:00 UTC
Labels: Bug, Unresolved, Pending closure
