### ISSUE TITLE
(python3) cygdb not found

### ISSUE THREAD

**Issue by kouhe3** [chocolatey-community/chocolatey-packages#1869] opened 2022-04-30 09:40 UTC
### Chocolatey Version

1.1.0

### Package Version

3.10.4

### Current Behaviour

Can not install Cython, cygdb.exe not found

![image](https://user-images.githubusercontent.com/25522053/166100080-5acaadcc-5907-4f8e-a96f-4fedd4e6b361.png)

### Steps To Reproduce

1. Create a new Windows 10/11 Virtual Machine
2. install choco
3. run `choco install python`
4. run `pip install Cython`

### Environment

```markdown
- Operating System 1: Windows 10 Pro x64 21H2 19044.1645 
- Operating System 2: Windows 11 Enterprise x64 21H2 22000.556
- PowerShell Version: pwsh 7.2.3 x64
```

### Chocolatey Log

```shell
https://gist.github.com/kouhe3/a71b2a0979a4c0db251d77e382b469c3
```

### Anything else?

If i use winget , instead of choco.
`winget install --id=Python.Python.3  -e`.
no problem

**Comment by AdmiringWorm** [comment] 2022-04-30 09:56
On Chocolatey the python directory is locked down, so it can not be written to by a normal user and requires an elevated shell when calling `pip`.

It sounds like you are trying to install `Cython` while running in a non-elevated shell, which by design won't allow the package files to be written to disk.

Can you try again while calling `pip` in an elevated shell?

**Comment by kouhe3** [comment] 2022-04-30 10:22
yes. You are right . pip install work in elevated shell.

I tried to install jupyter in non-elevated shell , and had the same problem.
`ERROR: Could not install packages due to an OSError: [WinError 2] can not found 'C:\\Python310\\Scripts\\send2trash.exe' -> 'C:\\Python310\\Scripts\\send2trash.exe.deleteme'`

but in elevated shell , I can install jupyter.

What is the difference between python installed by choco  and winget ?

**Comment by kouhe3** [comment] 2022-04-30 10:33
If I use choco to install python, will I need admin shell for every pip install in the future? 🤔

**Comment by AdmiringWorm** [comment] 2022-04-30 10:45
> What is the difference between python installed by choco and winget ?

To be completely honest, I do not know as I haven't checked how they are doing it in winget.
What I can say though, if the user do not install python3 to their own custom directory the entire folder will be locked down to admins only (this was in response to a abuse report we got a few years ago). If you uninstall python3 and then install it again while specifying the package parameter `/NoLockdown` then the folder will not be locked down to admins only (if you do not have the feature `useRememberedArgumentsForUpgrades` also enabled you need to specify that parameter on upgrades as well).

Do note that package parameters can not be passed in if you are installing through the `python` meta package, only if you install `python3` package directly.

> If I use choco to install python, will I need admin shell for every pip install in the future? 🤔

If you just install it and upgrade python3 package without specifying the nolockdown parameter, then yes. You will need to use admin shell every time.

Since this is working as intended in this case, I will be closing this issue as there is work around to also not make it admin only installations.

**Comment by AdmiringWorm** [comment] 2022-04-30 10:46
Lastly, just as a reference.
See the available package parameters on the description of the python3 package here: https://community.chocolatey.org/packages/python3

**Closed by AdmiringWorm** 2022-04-30 10:45 UTC
Labels: Bug, 0 - Waiting on User
