### ISSUE TITLE
(gitextensions) Should depend on dotnet-6.0-desktopruntime

### ISSUE THREAD

**Issue by TobiX** [chocolatey-community/chocolatey-packages#2092] opened 2022-12-19 11:01 UTC
### Chocolatey Version

1.2.1

### Chocolatey License

Business

### Package Version

4.0.1

### Current Behaviour

Currently, the Git Extensions package depends on `dotnet4.6.1`, after installing it you get a prompt to install the .NET Desktop runtime 6.x

### Expected Behaviour

No prompt to install additional software, Chocolatey should install all required dependencies, so the package should depend on `dotnet-6.0-desktopruntime`.

### Steps To Reproduce

1. `choco install gitextensions`
2. Run git extensions
3. Get error message

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19044.0
- PowerShell Version: 5.1.19041.2364
- Shell: PowerShell
```

### Chocolatey Log

```shell
2022-12-19 11:38:13,036 13784 [DEBUG] - ---------------------------Script Execution---------------------------
2022-12-19 11:38:13,040 13784 [DEBUG] - Running 'ChocolateyScriptRunner' for gitextensions v4.0.1 with packageScript 'C:\ProgramData\chocolatey\lib\gitextensions\tools\chocolateyInstall.ps1', packageFolder:'C:\ProgramData\chocolatey\lib\gitextensions', installArguments: '', packageParameters: '', preRunHookScripts: '', postRunHookScripts: '',
2022-12-19 11:38:13,040 13784 [DEBUG] - Running package script 'C:\ProgramData\chocolatey\lib\gitextensions\tools\chocolateyInstall.ps1'
2022-12-19 11:38:13,061 13784 [DEBUG] - Running licensed 'Install-ChocolateyInstallPackage' for gitextensions with File:'C:\ProgramData\chocolatey\lib\gitextensions\tools\GitExtensions-4.0.1.15887-f2567dea2.msi', File64:'', SilentArguments:'/quiet /norestart ADDDEFAULT=ALL REMOVE=AddToPath', InstallerType:'msi', ValidExitCodes:'0,3010,1641', UseOnlyPackageSilentArguments:'False' AnswerFile:''
2022-12-19 11:38:13,110 13784 [INFO ] - Installing GitExtensions-4.0.1.15887-f2567dea2.msi...
2022-12-19 11:38:13,120 13784 [DEBUG] - Running licensed 'Start-ChocolateyProcessAsAdmin' with ExeToRun:'C:\WINDOWS\System32\msiexec.exe', Statements:'/i "C:\ProgramData\chocolatey\lib\gitextensions\tools\GitExtensions-4.0.1.15887-f2567dea2.msi" /quiet /norestart ADDDEFAULT=ALL REMOVE=AddToPath', Elevated:'True', Minimized:'False', NoSleep:'False', ValidExitCodes: '0,3010,1641', WorkingDirectory:'C:\ProgramData\chocolatey\lib\gitextensions\tools', AnswerFile:'' Has SensitiveStatements:'False'
2022-12-19 11:38:13,178 13784 [DEBUG] - Running ['C:\WINDOWS\System32\msiexec.exe' /i "C:\ProgramData\chocolatey\lib\gitextensions\tools\GitExtensions-4.0.1.15887-f2567dea2.msi" /quiet /norestart ADDDEFAULT=ALL REMOVE=AddToPath]. This may take a while, depending on the statements.
2022-12-19 11:38:16,056 13784 [DEBUG] - Command ['C:\WINDOWS\System32\msiexec.exe' /i "C:\ProgramData\chocolatey\lib\gitextensions\tools\GitExtensions-4.0.1.15887-f2567dea2.msi" /quiet /norestart ADDDEFAULT=ALL REMOVE=AddToPath] exited with '0'
2022-12-19 11:38:16,060 13784 [DEBUG] - Finishing licensed 'Start-ChocolateyProcessAsAdmin'
2022-12-19 11:38:16,060 13784 [INFO ] - GitExtensions-4.0.1.15887-f2567dea2.msi has been installed.
2022-12-19 11:38:16,070 13784 [INFO ] - VERBOSE: Trying local and machine (x32 & x64) Uninstall keys
2022-12-19 11:38:16,090 13784 [DEBUG] - Running Get-UninstallRegistryKey -softwareName 'GitExtensions' 
2022-12-19 11:38:16,095 13784 [INFO ] - VERBOSE: Retrieving all uninstall registry keys
2022-12-19 11:38:16,190 13784 [DEBUG] - Registry uninstall keys on system: 200
2022-12-19 11:38:16,190 13784 [DEBUG] - Error handling check: 'Get-ItemProperty' fails if a registry key is encoded incorrectly.
2022-12-19 11:38:16,269 13784 [WARN ] - WARNING: No registry key found based on  'GitExtensions'
2022-12-19 11:38:16,269 13784 [DEBUG] - Found 0 uninstall registry key(s) with SoftwareName:'GitExtensions'
2022-12-19 11:38:16,269 13784 [INFO ] - VERBOSE: Found 0 keys, aborting this method
2022-12-19 11:38:16,280 13784 [DEBUG] - Running Get-OSArchitectureWidth -compare '64' 
2022-12-19 11:38:16,280 13784 [INFO ] - VERBOSE: Trying Program Files with 2 levels depth: C:\Program Files C:\Program Files\*\* C:\Program Files (x86) C:\Program Files (x86)\*\*
2022-12-19 11:38:16,479 13784 [DEBUG] - Running Install-BinFile -name 'gitex' -path 'C:\Program Files (x86)\GitExtensions\gitex.cmd' 
2022-12-19 11:38:16,491 13784 [DEBUG] - ShimGen found at 'C:\ProgramData\chocolatey\tools\shimgen.exe'
2022-12-19 11:38:16,492 13784 [DEBUG] - Calling C:\ProgramData\chocolatey\tools\shimgen.exe -o "C:\ProgramData\chocolatey\bin\gitex.exe" -p "c:\program files (x86)\gitextensions\gitex.cmd" -i "C:\Program Files (x86)\GitExtensions\gitex.cmd"
2022-12-19 11:38:16,697 13784 [INFO ] - Added C:\ProgramData\chocolatey\bin\gitex.exe shim pointed to 'c:\program files (x86)\gitextensions\gitex.cmd'.
2022-12-19 11:38:16,702 13784 [DEBUG] - ----------------------------------------------------------------------
2022-12-19 11:38:16,705 13784 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\gitextensions\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '' -preRunHookScripts $null -postRunHookScripts $null'] exited with '0'.
2022-12-19 11:38:16,708 13784 [DEBUG] - Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
2022-12-19 11:38:16,760 13784 [DEBUG] - Command ['"C:\WINDOWS\System32\shutdown.exe" /a'] exited with '1116'
2022-12-19 11:38:16,797 13784 [INFO ] -   gitextensions may be able to be automatically uninstalled.
2022-12-19 11:38:16,803 13784 [WARN ] - Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
2022-12-19 11:38:16,805 13784 [DEBUG] - Logging of values is not turned on by default because it
 could potentially expose sensitive data. If you understand the risk,
 please see `choco feature -h` for information to turn it on.
2022-12-19 11:38:16,808 13784 [DEBUG] - The following values have been added/changed (may contain sensitive data):
2022-12-19 11:38:16,812 13784 [DEBUG] -   * Path='[REDACTED]' (Machine)
2022-12-19 11:38:16,842 13784 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\gitextensions'
2022-12-19 11:38:16,880 13784 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\gitextensions\gitextensions.nupkg'
  with checksum 'B3DC12D663D4077CA5B8B6A7DB0DFAC6'
2022-12-19 11:38:16,884 13784 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\gitextensions\gitextensions.nuspec'
  with checksum 'D72EE034BE14CFA3A5754DB1526FC3AD'
2022-12-19 11:38:16,884 13784 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\gitextensions\legal\LICENSE.md'
  with checksum 'C65BD98A28A1650EA6C957EE51B1A341'
2022-12-19 11:38:16,889 13784 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\gitextensions\legal\VERIFICATION.txt'
  with checksum 'B30744F961CF02CA934F070E7814B576'
2022-12-19 11:38:16,891 13784 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\gitextensions\tools\chocolateyInstall.ps1'
  with checksum '3F402A121EC1052261FD0B7441ACC3F9'
2022-12-19 11:38:16,892 13784 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\gitextensions\tools\chocolateyUninstall.ps1'
  with checksum 'C7DA3C46F45B6C0D5191699AF6BDD48B'
2022-12-19 11:38:16,936 13784 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\gitextensions\tools\GitExtensions-4.0.1.15887-f2567dea2.msi'
  with checksum '6479E68F4E46E91EF1A19F9659D63500'
2022-12-19 11:38:16,937 13784 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\gitextensions\tools\GitExtensions-4.0.1.15887-f2567dea2.msi.ignore'
  with checksum 'ECAA88F7FA0BF610A5A26CF545DCD3AA'
2022-12-19 11:38:16,952 13784 [INFO ] -  Reducing package size for 'gitextensions'...
2022-12-19 11:38:16,954 13784 [DEBUG] - Attempting to create directory "C:\Users\Administrator\AppData\Local\Temp\chocolatey\ChocolateyPackageCache\PackageCache_20221219_113816_9511".
2022-12-19 11:38:16,956 13784 [DEBUG] - Attempting to copy "C:\ProgramData\chocolatey\lib\gitextensions\gitextensions.nuspec"
 to "C:\Users\Administrator\AppData\Local\Temp\chocolatey\ChocolateyPackageCache\PackageCache_20221219_113816_9511\gitextensions.nuspec".
2022-12-19 11:38:17,090 13784 [INFO ] -  Reducing nupkg file size ('gitextensions').
2022-12-19 11:38:17,114 13784 [INFO ] -  Reducing extracted archives and installers ('gitextensions').
2022-12-19 11:38:17,116 13784 [INFO ] -  Removing 'C:\ProgramData\chocolatey\lib\gitextensions\tools\GitExtensions-4.0.1.15887-f2567dea2.msi' ('gitextensions').
2022-12-19 11:38:17,117 13784 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\gitextensions\tools\GitExtensions-4.0.1.15887-f2567dea2.msi".
2022-12-19 11:38:17,122 13784 [INFO ] -  Space reduced for 'gitextensions': 40,53 MB.
2022-12-19 11:38:17,122 13784 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\gitextensions\gitextensions.nupkg.bkp".
2022-12-19 11:38:17,144 13784 [DEBUG] - There was no original file at 'C:\ProgramData\chocolatey\.chocolatey\gitextensions.4.0.1\.registry'
2022-12-19 11:38:17,145 13784 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\gitextensions.4.0.1\.extra".
2022-12-19 11:38:17,150 13784 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\gitextensions.4.0.1\.version".
2022-12-19 11:38:17,150 13784 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\gitextensions.4.0.1\.sxs".
2022-12-19 11:38:17,150 13784 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\gitextensions.4.0.1\.pin".
2022-12-19 11:38:17,157 13784 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
2022-12-19 11:38:17,158 13784 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\lib\gitextensions\.chocolateyPending".
2022-12-19 11:38:17,161 13784 [INFO ] -  The install of gitextensions was successful.
2022-12-19 11:38:17,163 13784 [INFO ] -   Software install location not explicitly set, it could be in package or
  default install location of installer.
2022-12-19 11:38:17,166 13784 [DEBUG] - Attempting to delete file "C:\Users\Administrator\AppData\Local\NuGet\Cache\gitextensions.4.0.1.nupkg".
2022-12-19 11:38:17,175 13784 [WARN ] - 
Chocolatey installed 1/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2022-12-19 11:38:17,180 13784 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
```

**Comment by pauby** [comment] 2023-01-15 20:00
#2111 is actually a duplicate of this one and should have been closed. However, I raised a PR against that so closing this one in favour of that.

**Closed by pauby** 2023-01-15 20:00 UTC
Labels: Bug
