### ISSUE TITLE
paint.net.portable

### ISSUE THREAD

**Issue by jmeile** [chocolatey-community/chocolatey-packages#2201] opened 2023-03-28 17:24 UTC
### Chocolatey Version

1.3.1

### Chocolatey License

None

### Package Version

5.0.2

### Current Behaviour

Closing the application last 10 seconds. The non-portable version closes immediately.

### Expected Behaviour

Application closing without delay

### Steps To Reproduce

1. Open Paint.net
2. Close Paint.net and wait 10 seconds
3. Paint.net will be closed

### Environment

```markdown
- Operating System: Microsoft Windows NT 10.0.19042.0
- PowerShell Version: 5.1.19041.2673
```

### Chocolatey Log

```shell
Not really an installation issue, so, the log isn't needed here
```

### Anything else?

The portables from here:
https://github.com/paintdotnet/release/releases/download/v5.0.2/paint.net.5.0.2.portable.x64.zip
https://portableapps.com/apps/graphics_pictures/paintdotnet-portable

don't have this problem

**Comment by pauby** [comment] 2023-03-28 17:36
I can't reproduce this. Closes immediately for me. Have you reproduced this on another system?

![WindowsSandboxClient_Dm41d27ZpE](https://user-images.githubusercontent.com/12760779/228321945-9bfdaa14-e28c-49a7-9e7b-4ff18823e4ee.gif)

**Comment by AdmiringWorm** [comment] 2023-03-29 03:51
We do not maintain this package. Only packages that list the user `chocolatey-community` as a package maintainer are supported in this repository.

To fix any issues for packages not maintained in this repository, you must contact the package's maintainer either by using `Contact Maintainers` or navigating to their listed `Package Source`.
Both of these are listed on the details page for the package.

As we do not maintain this package, I will close this issue.

**Closed by AdmiringWorm** 2023-03-29 03:51 UTC
Labels: Bug, 0 - Waiting on User

**Comment by pauby** [comment] 2023-03-29 10:40
I didn't. Even. Notice. That. 😨 Apologies.

![image](https://user-images.githubusercontent.com/12760779/228508989-90a6bb5a-d760-40e7-b985-d935be44c71b.png)
