### ISSUE TITLE
(openshift-cli) is outdated

### ISSUE THREAD

**Issue by upr-kmd** [chocolatey-community/chocolatey-packages#1983] opened 2022-09-13 15:24 UTC
### Checklist

- [X] I have checked the moderation queue that no new version has been submitted (only visible when logged in), or the submitted package version has failed the automated checks.

Please navigate to the following [link](https://community.chocolatey.org/packages?q=&moderatorQueue=true&moderationStatus=all-statuses&prerelease=false&sortOrder=package-download-count) to view the moderation queue.

- [X] I have verified that the new version is a stable release.
- [X] I have looked to see if there are any Bug reports that prevents a new version being submitted and that no existing Outdated Reports have been created.
- [X] I have verified the new version has a Windows binary (EXE or MSI installer, Zip or other archive, etc).

### New Software Version

4.11.4

### Download location

https://access.redhat.com/downloads/content/290/ver=4.11/rhel---8/4.11.4/x86_64/product-software

### Package Page

https://community.chocolatey.org/packages/openshift-cli

**Comment by brogers5** [comment] 2022-09-18 23:25
Possible duplicate of #1601.

The provided download location is hidden behind a Red Hat account login with an active paid subscription, and likely unusable for the package's purposes.

The location provided in the other issue has since been deprecated. However, it does have a text file pointing toward this as a successor:
https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/

The [stable channel](https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/) is currently pointing to 4.11.3, but 4.11.4 is the current release for the [fast channel](https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/fast/). Version availability may lag accordingly if an updated package ends up targeting the stable channel exclusively.

**Comment by pauby** [comment] 2022-10-25 17:55
@upr-kmd Are you in a position to update this package and submit a pull request?

**Comment by upr-kmd** [comment] 2022-10-27 11:44
Unfortunately not. I don't know how to build chocolatey packages.

**Comment by JPRuskin** [comment] 2022-10-27 16:44
Assuming the site is allowable, I think we could use https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/release.txt to find the latest release, and then use the link from the correct folder https://mirror.openshift.com/pub/openshift-v4/clients/ocp/ + $Version ...

I'll get this sorted.

**Closed** 2022-12-16 09:30 UTC
Labels: Outdated
