### ISSUE TITLE
VirtualBox

### ISSUE THREAD

**Issue by awatchanaman** [chocolatey-community/chocolatey-packages#2132] opened 2023-01-26 12:50 UTC
### Chocolatey Version

0.12.1

### Chocolatey License

None

### Package Version

7.0.6

### Current Behaviour

the software does not install because the hash of the virtual box extension is not the correct one

### Expected Behaviour

the software installs

### Steps To Reproduce

1/ windows
2/ not install extension
2/ error Hash

### Environment

```markdown
- Operating System: windows
- PowerShell Version: 
- Shell:
```

### Chocolatey Log
Could not update: Execution of 'C:\ProgramData\chocolatey\choco.exe install virtualbox -y -params " /NoDesktopShortcut /ExtensionPack " --ignore-package-exit-codes --no-progress' returned 1: Chocolatey v1.1.0 Installing the following packages: virtualbox By installing, you accept licenses for the packages. virtualbox v7.0.6 virtualbox package files install completed. Performing other installation steps. Param: No desktop shortcut Downloading virtualbox 64 bit from Download of VirtualBox-7.0.6-155176-Win.exe (105.34 MB) completed. Hashes match. Installing virtualbox... virtualbox has been installed. Installing extension pack WARNING: *** THIS IS A COMMERCIAL EXTENSION AND CAN INCURE SIGNIFICANT FINANCIAL COSTS *** Downloading virtualbox-extensionpack 64 bit from 'https://download.virtualbox.org/virtualbox/7.0.6/Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack' WARNING: C:\WINDOWS\TEMP\chocolatey\virtualbox\7.0.6\Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack is of content type text/plain Download of Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack (17.68 MB) completed. Error - hashes do not match. Actual value was '292961AA8723B54F96F89F6D8ABF7D8E29259D94B7DE831DBFFB9AE15D346434'. ERROR: Checksum for 'C:\WINDOWS\TEMP\chocolatey\virtualbox\7.0.6\Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack' did not meet '21c3595361bb2365efe6139f1da724d362daa63fb92c38f686a01aa9200628b2' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary. virtualbox may be able to be automatically uninstalled. The install of virtualbox was NOT successful. Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'. See log for details. Chocolatey installed 0/1 packages. 1 packages failed. See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log). Failures - virtualbox (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'. See log for details.
```shell
bas hash (extention virtual box)
```

**Comment by pauby** [comment] 2023-01-26 13:06
We are unable to reproduce the issue if we cannot go through the steps.

Can you go back and update both the `Steps to Reproduce` and `Chocolatey Log`?

**Comment by awatchanaman** [comment] 2023-01-27 09:42
Hello, i understand: steps to reproduce:

virtual box 7.0.4 already installed on the Windows 10 workstation, the installation of the new version 7.0.6 blocks. here is the log:

<html><body>


Could not update: Execution of 'C:\ProgramData\chocolatey\choco.exe install virtualbox -y -params " /NoDesktopShortcut /ExtensionPack " --ignore-package-exit-codes --no-progress' returned 1: Chocolatey v1.1.0 Installing the following packages: virtualbox By installing, you accept licenses for the packages.  virtualbox v7.0.6 virtualbox package files install completed. Performing other installation steps. Param: No desktop shortcut Downloading virtualbox 64 bit   from 'https://repo.usm.su.univ-lorraine.fr:8443/repository/internal-sources/virtualbox/7.0.6/VirtualBox-7.0.6-155176-Win.exe'  Download of VirtualBox-7.0.6-155176-Win.exe (105.34 MB) completed. Hashes match. Installing virtualbox... virtualbox has been installed. Installing extension pack WARNING: *** THIS IS A COMMERCIAL EXTENSION AND CAN INCURE SIGNIFICANT FINANCIAL COSTS *** Downloading virtualbox-extensionpack 64 bit   from 'https://download.virtualbox.org/virtualbox/7.0.6/Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack' WARNING: C:\WINDOWS\TEMP\chocolatey\virtualbox\7.0.6\Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack is of content type text/plain  Download of Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack (17.68 MB) completed. Error - hashes do not match. Actual value was '292961AA8723B54F96F89F6D8ABF7D8E29259D94B7DE831DBFFB9AE15D346434'. ERROR: Checksum for 'C:\WINDOWS\TEMP\chocolatey\virtualbox\7.0.6\Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack' did not meet '21c3595361bb2365efe6139f1da724d362daa63fb92c38f686a01aa9200628b2' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.   virtualbox may be able to be automatically uninstalled. The install of virtualbox was NOT successful. Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'.  See log for details.  Chocolatey installed 0/1 packages. 1 packages failed.  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).  Failures  - virtualbox (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'.  See log for details. |  
-- | --



</body>
</html>

**Comment by awatchanaman** [comment] 2023-02-01 08:19
> We are unable to reproduce the issue if we cannot go through the steps.
> 
> Can you go back and update both the `Steps to Reproduce` and `Chocolatey Log`? Can you also update the title to be more descriptive as per the notes in the issue template?



Hello, i understand: steps to reproduce:

virtual box 7.0.4 already installed on the Windows 10 workstation, the installation of the new version 7.0.6 blocks. here is the log:
Could not update: Execution of 'C:\ProgramData\chocolatey\choco.exe install virtualbox -y -params " /NoDesktopShortcut /ExtensionPack " --ignore-package-exit-codes --no-progress' returned 1: Chocolatey v1.1.0 Installing the following packages: virtualbox By installing, you accept licenses for the packages. virtualbox v7.0.6 virtualbox package files install completed. Performing other installation steps. Param: No desktop shortcut Downloading virtualbox 64 bit from 'https://repo.usm.su.univ-lorraine.fr:8443/repository/internal-sources/virtualbox/7.0.6/VirtualBox-7.0.6-155176-Win.exe' Download of VirtualBox-7.0.6-155176-Win.exe (105.34 MB) completed. Hashes match. Installing virtualbox... virtualbox has been installed. Installing extension pack WARNING: *** THIS IS A COMMERCIAL EXTENSION AND CAN INCURE SIGNIFICANT FINANCIAL COSTS *** Downloading virtualbox-extensionpack 64 bit from 'https://download.virtualbox.org/virtualbox/7.0.6/Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack' WARNING: C:\WINDOWS\TEMP\chocolatey\virtualbox\7.0.6\Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack is of content type text/plain Download of Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack (17.68 MB) completed. Error - hashes do not match. Actual value was '292961AA8723B54F96F89F6D8ABF7D8E29259D94B7DE831DBFFB9AE15D346434'. ERROR: Checksum for 'C:\WINDOWS\TEMP\chocolatey\virtualbox\7.0.6\Oracle_VM_VirtualBox_Extension_Pack-7.0.6.vbox-extpack' did not meet '21c3595361bb2365efe6139f1da724d362daa63fb92c38f686a01aa9200628b2' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary. virtualbox may be able to be automatically uninstalled. The install of virtualbox was NOT successful. Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'. See log for details. Chocolatey installed 0/1 packages. 1 packages failed. See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log). Failures - virtualbox (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'. See log for details.

**Comment by pauby** [comment] 2023-02-01 12:49
@awatchanaman You need to **go back to your original comment and add the information requested in there**.

**Comment by awatchanaman** [comment] 2023-02-01 12:57
ok now can you answer me if you are going to modify the package?

**Comment by pauby** [comment] 2023-02-01 19:51
A new version was pushed. Closing this.

**Closed by pauby** 2023-02-01 19:51 UTC
Labels: Bug, 0 - Waiting on User

**Comment by ffloimair** [comment] 2023-02-02 17:38
This new version (7.0.6.20230201) is flawed.

First of all it reinstalls 7.0.6 over an already existing 7.0.6 and fails in doing so without being very verbose about it:
`VirtualBox-7.0.6-155176-Win.exe: error: Installation failed! Error: Schwerwiegender Fehler bei der Installation.
Microsoft.PowerShell.Commands.WriteErrorException
ERROR: Running ["C:\Users\myuser\AppData\Local\Temp\chocolatey\virtualbox\7.0.6.20230201\VirtualBox-7.0.6-155176-Win.exe" -s -l -msiparams REBOOT=ReallySuppress ALLUSERS=1 ] was not successful. Exit code was '1'. See log for possible error messages.
The upgrade of virtualbox was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\virtualbox\tools\chocolateyInstall.ps1'.
 See log for details.`

Aside from redownloading an already installed 7.0.6 version, what's the point of the semantic versioning? Upstream does not use it.

**Comment by pauby** [comment] 2023-02-02 18:40
Just to be clear, the package isn't 'flawed'. The package is doing what it is supposed to do.

Version 7.0.6 _package_ is installed. You are installing package version 7.0.6.20230201, so the package runs the install script which runs the installer. The installer fails because it's already installed.

When the package fix version was pushed we didn't know the installer behaved in this way. Perhaps there should be additional logic in the package. My suggestion would be to submit a PR to add that.

**Comment by pauby** [comment] 2023-02-02 19:39
If I understand the issue it will happen if you upgrade it explicitly or with `all`.

Why is it different for you?

**Comment by ffloimair** [comment] 2023-02-02 23:34
Well the difference is simple: Before only "real updates" were installed (e.g. 7.0.4 -> 7.0.6), no it tries to reinstall 7.0.6 because it "thinks" 7.0.6.20230201 is newer which it isn't. It's exactly the same.
This is why I think it's a bad idea to use this new chocolatey exclusive semver (20230201) as it does not match the "official" versions from virtualbox.org.
What I would expect is, that it works like before: Only update if there are updates available from virtualbox.org

**Comment by pauby** [comment] 2023-02-03 10:49
That's why [this issue](https://github.com/chocolatey-community/chocolatey-packages/issues/2137) was created.
